### ISSUE TITLE
Tracking upstream projects that do not support hermetic-usr for configuration

### ISSUE THREAD

**Issue by bluca** [uapi-group/specifications#76]
This issue will be used to track Linux projects that do not currently support hermetic-usr configuration style (ie: /usr/foo as default, /run/foo as ephemeral local override, /etc/foo as persistent local override). The purpose is to have a cross-distribution list of items to slowly work through, to be able to have a bootable and working minimal Linux image-based system with only /usr.

- <TODO: actual list, placeholder for now>

**Comment by thkukuk** [comment]
A first bunch, starting with a minimal OS running containers.
* update-alternatives (from dpkg) uses /etc/alternatives. There is https://github.com/openSUSE/libalternatives but this only works for binaries, not e.g. manual pages
* selinux-policy installs the policy in /etc/selinux/<policy> and /var/lib/selinux/<policy>. Especially the last is a problem, as this mixes user changes with policy defaults. /var/lib/selinux needs to be splitted: the package defaults belongs somewhere to /usr, which should be merged with the admin changes (should be stored in /etc/, not /var) at runtime.
* sudo has /etc/sudo.conf, /etc/sudoers and /etc/sudo_logsrvd.conf
* audit (/etc/audit/auditd.conf, /etc/libaudit.conf)
* rsync (/etc/rsyncd.conf)
* chrony (/etc/chrony.conf)
* podman and releated tools/libraries (/etc/containers)

**Comment by julian-klode** [comment]
APT and dpkg both don't support it. I haven't figured out the behavior for APT yet, tbh, it's weird because essentially everything is drop-ins for apt.conf these days.

**Comment by thkukuk** [comment]
> glibc for /etc/services (used by getservbyname/getservbyport, which make little sense and are not widely used, but there still are some applications which do). It should be moved under /usr.

`getservbyname/getservbyport`  are using NSS as backend. There are NSS modules for nearly every location, not only `/etc/services`, NIS or LDAP, but also for `/usr`.  There is e.g. https://github.com/openSUSE/libnss_usrfiles, which, with the `/etc/nsswitch.conf` option `services: files usrfiles` looks at first for entries in `/etc/services` and afterwards in `/usr/etc/services`.  More such modules exists, so in my opinion, this task is solved, it's just in the responsibility of the Linux distributior to package the best fitting variant and configure it. openSUSE Tumbleweed/MicroOS are doing this since many years.
So this is solved for aliases, ethers, protocols, rpc and services.
`/etc/shells` is not handled by NSS, so solving that will be more complicated.

**Comment by fbuihuu** [comment]
I dare to add to the list  :

- [ ] systemd ships all its main config files in /etc/systemd or /etc/udev.

There's currently https://github.com/systemd/systemd/pull/28919 to address this issue by giving the possibility to downstream to ship the config files in /usr/lib but for some reasons the idea has not been well received.

**Comment by fbuihuu** [comment]
- [  ] udev (/etc/udev/udev.conf)

**Comment by poettering** [comment]
@fbuihuu systemd's config files in /etc/ are just decoration. Entirely redundant, they are pretty much just helpful hints to people who want to sue traditional populated /etc/. If you delete them for modern systems that come up without /etc/ then behaviour is not changed whatsoever.

All options listed in them just give users hints on the available settings and their defaults, and those options are fully commented, hence these files are NOPs.

**Comment by thkukuk** [comment]
Next package list:
* glibc:
  * /etc/nsswitch.conf (https://bugzilla.suse.com/show_bug.cgi?id=1215487)
  * /etc/host.conf
  * /etc/rpc
  * ldconfig (/etc/ld.so.conf, /etc/ld.so.conf.d, but no /usr/...)
* mailx (/etc/mail.rc)
* util-linux (/etc/blkid.conf)
* fcoe-utils (/etc/fcoe/)
* SELinux
  * policycoreutils/sestatus (/etc/sestatus.conf)
* open-iscsi (/etc/iscsi/iscsid.conf)
* krb5 (/etc/krb5.conf)
* libnl (/etc/libnl/)
* libssh (/etc/libssh/)
* e2fsprogs (/etc/mke2fs.conf)
* nftables (/etc/nftables/)
* smartmontools (/etc/smartd.conf, /etc/smartd_warning.sh)
* wpa_supplicant (/etc/wpa_supplicant/wpa_supplicant.conf)
* attr (/etc/xattr.conf)
* zypper (/etc/zypp/zypp.conf, /etc/zypp/zypper.conf)

**Comment by thkukuk** [comment]
For glibc I missed yesterday:
* nscd (/etc/nscd.conf)

This are now all packages from our minimal installation of MicroOS as ContainerHost beside openssh.
I spoke already with the openssh developers about this some time ago, they rejected all ideas to modify configuration file handling. So we (openSUSE) reconfigured the configuration file setup to mimic hermetic-usr as far as possible, open issue is `AcceptEnv`, which you cannot overwrite.

Question is how far do we want to go with that list? I could go as next through a typical server installation and desktop system, but I don't know if this would be really helpful, as the list is already long and it would mix up packages with different priority.

**Comment by bluca** [comment]
> This are now all packages from our minimal installation of MicroOS as ContainerHost beside openssh. I spoke already with the openssh developers about this some time ago, they rejected all ideas to modify configuration file handling. So we (openSUSE) reconfigured the configuration file setup to mimic hermetic-usr as far as possible, open issue is `AcceptEnv`, which you cannot overwrite.

Yeah I had the same experience some years past, openssh as a project is just not interested in anything that doesn't directly benefit BSD. Should we set up a Linux-focused fork, where we can co-maintain patches?

> Question is how far do we want to go with that list? I could go as next through a typical server installation and desktop system, but I don't know if this would be really helpful, as the list is already long and it would mix up packages with different priority.

I think this is a good starting point, being core packages they are the highest value to fix. Once we have made a dent in the current list, then we could start looking at a server installation.

**Comment by ReillyBrogan** [comment]
Apparmor is another one that doesn't support any kind of vendordir at the moment.

**Comment by schubi2** [comment]
I have fixed mailx (/etc/mail.rc) in SUSE OBS: https://build.opensuse.org/request/show/1131341
I would like to do it upstream too, but I do not find the code stream to which I can make a PR.
Does anyone know where mailx is hosted upstream ?
I know, it is really old code :-)

**Comment by bluca** [comment]
In Debian we ship bsd-mailx: https://tracker.debian.org/pkg/bsd-mailx which according to package metadata comes from https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/mail/

**Comment by schubi2** [comment]
> In Debian we ship bsd-mailx: https://tracker.debian.org/pkg/bsd-mailx which according to package metadata comes from https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/mail/

Thanks for hint ! I have sent a patch to tech@openbsd.org .

**Comment by poettering** [comment]
I filed this bug against Fedora's authselect now:

https://github.com/authselect/authselect/issues/355

**Comment by schubi2** [comment]
I have submitted a patch for selinux:
https://github.com/SELinuxProject/selinux/pull/415

**Comment by Conan-Kudo** [comment]
DNF 5 supports hermetic configuration since 5.1.4.

https://github.com/rpm-software-management/dnf5/pull/813
https://github.com/rpm-software-management/dnf5/pull/820
https://github.com/rpm-software-management/dnf5/pull/882

**Comment by keszybz** [comment]
> [rpm-software-management/dnf5#813](https://github.com/rpm-software-management/dnf5/pull/813)
> [rpm-software-management/dnf5#820](https://github.com/rpm-software-management/dnf5/pull/820)
> [rpm-software-management/dnf5#882](https://github.com/rpm-software-management/dnf5/pull/882)

Thanks. I filed https://github.com/rpm-software-management/dnf5/issues/1107.

**Comment by DaanDeMeyer** [comment]
What about ca-certificates? That one seems to be prominently missing from the list? Debian already seems to put certificates in /usr/share/ca-certificates, whereas Fedora uses /etc/pki and OpenSUSE /var/lib/ca-certificates? It'd be great if we could standardize on /usr/share/ca-certificates in some form (not familiar with the details)

**Comment by schubi2** [comment]
I have submitted a patch for open-iscsi:
https://github.com/open-iscsi/open-iscsi/pull/437

**Comment by Conan-Kudo** [comment]
> What about ca-certificates? That one seems to be prominently missing from the list? Debian already seems to put certificates in /usr/share/ca-certificates, whereas Fedora uses /etc/pki and OpenSUSE /var/lib/ca-certificates? It'd be great if we could standardize on /usr/share/ca-certificates in some form (not familiar with the details)

A `/usr/share/pki` hierarchy as an equivalent to the one in `/etc/pki` would allow moving most of this stuff.

**Comment by DaanDeMeyer** [comment]
Another one that seems to be missing is openssl

**Comment by keszybz** [comment]
Since dnf5 gained support, I filed the following:
https://src.fedoraproject.org/rpms/systemd/c/bedc0270e72071dd027f998629f6d633700c5b89
https://src.fedoraproject.org/rpms/setup/pull-request/12
https://src.fedoraproject.org/rpms/sudo/pull-request/29

**Comment by keszybz** [comment]
I marked those as fixed:
> systemd "empty" main config files in /etc/systemd
> udev "empty" main config files in /etc/udev

https://github.com/systemd/systemd/commit/6495361c7d added the functionality to systemd.
https://src.fedoraproject.org/rpms/systemd/c/29eb35530b and https://src.fedoraproject.org/rpms/systemd/c/4c7acded2a make use of this in Fedora.

**Comment by poettering** [comment]
I posted patches to glibc mailing list that teaches glibc NSS to look in /usr/share/ for its various database files, such as /etc/protocols (which will now be looked for in /usr/share/protocols too):

https://sourceware.org/pipermail/libc-alpha/2024-September/160190.html

Let's see if this has any chance to get in.

**Comment by DaanDeMeyer** [comment]
@poettering No nsswitch.conf?

**Comment by cgwalters** [comment]
Two notes:

- The nss-altfiles model is additive with /etc, which is a different thing (and often desirable)
- There is also /usr/lib/passwd vs /usr/share/passwd here too (which is fine, I think we actually need to do that to be compatible with systems using nss-altfiles today)

**Comment by poettering** [comment]
> @poettering No nsswitch.conf?

For now, not. This one only moves the NSS databases. If this works out I'll look into moving non-database files too, i.e. nsswitch.conf, ld.so.conf, resolv.conf, host.conf, shells. (Won't bother with nscd.conf, because nscd is obsolete, and /etc/rpc is not a concept i grok)

**Comment by poettering** [comment]
> Two notes: 
> * The nss-altfiles model is additive with /etc, which is a different thing (and often desirable) 

Ah, interesting. Weirdly, /etc/aliases (and only that) in glibc's enumeration logic contains an "include" logic. if /etc/passwd had that you could use that i guess.. 

But I guess people who have both sets of files and want them merged should just continue to use nss-altfiles. I'll mention this in an updated commit msg, should i need to update the patch.

> * There is also /usr/lib/passwd vs /usr/share/passwd here too (which is fine, I think we actually need to do that to be compatible with systems using nss-altfiles today)

In my view of the world, stuff private to some package should be in `/usr/lib/<package>`, and stuff shared between packages should be in `/usr/share/`, hence I picked the latter here, because these files have various stakeholders I guess.

**Comment by cgwalters** [comment]
One thing I'd known for a while, but came up as part of the glibc patch is that there's a conflict between what OpenSUSE has been doing and what ostree has been doing. Basically that conflict is that ostree unconditionally has `/usr/etc` be what was installed by project as `/etc` - it's somewhat of an implementation detail (and yes arguably it should have been `/usr/lib/ostree/default-etc` or something, but I had also hoped to make it a standard but never drove that well...a lack of will for coordination on my part, also long predates uapi etc).

The conflict is that in the ostree model we can't have *both* `/etc` and `/usr/etc` in the image, because it's ostree that owns merging `/usr/etc` with `/etc`.

Anyways, let me summarize this briefly here (but we should file a dedicated tracker here perhaps?); there are basically at least 4 major approaches to /etc I know of:

- What is promoted here, `/etc` starts out empty (let's call this the "uapi ideal", though I'm not entirely sure it's truly my ideal, but that's an aside)
- What flatcar is doing (overlayfs for `/etc` with the lower being the defaults as installed by upstream, and `/etc` is a mutable persistent overlayfs upper)
- What ostree is doing; a userspace 3 way merge; I *think* this is equivalent or almost equivalent to the flatcar approach (gotta remember, ostree long predates overlayfs, the ubiquitous Swiss Army knife for filesystem tricks we do today)
- What OpenSUSE is doing (I don't quite know exactly, but it seems to rely on having upstreams install stuff in `/usr/etc`)

The first observation I will make is that the "uapi ideal" is generally compatible with the other 3. The other 3 are attempts to deal with the fact that we don't live in that "uapi ideal" (and honestly, I doubt my use cases will before I retire...).

What I think we really need to resolve here is the conflict between the OpenSUSE approach and the ostree one because we are giving upstreams conflicting guidance. It seems to me that *both* should change. I think OpenSUSE should stop encouraging people to put `/etc/foo.conf` in `/usr/etc/foo.conf` because when we're doing a move and patching upstreams anyways, let's clean up the name spacing here and have it be `/usr/lib/foo/foo.conf` or so.

I may also change ostree...I need to dig in some but the flatcar model seems appealing. Or in the short term (it may be painful) I could try to change ostree to use `/usr/lib/ostree/default-etc` or so.

For example https://github.com/uapi-group/specifications/issues/100 making things conditional to move to `/usr/etc` are too crude IMO.

**Comment by thkukuk** [comment]
On Fri, Sep 27, 2024 at 1:51 PM Colin Walters ***@***.***>
wrote:

> One thing I'd known for a while, but came up as part of the glibc patch is
> that there's a conflict between what OpenSUSE has been doing and what
> ostree has been doing. Basically that conflict is that ostree
> unconditionally has /usr/etc be what was installed by project as /etc -
> it's somewhat of an implementation detail (and yes arguably it should have
> been /usr/lib/ostree/default-etc or something, but I had also hoped to
> make it a standard but never drove that well...a lack of will for
> coordination on my part, also long predates uapi etc).
>
> The conflict is that in the ostree model we can't have *both* /etc and
> /usr/etc in the image, because it's ostree that owns merging /usr/etc
> with /etc.
>
> Anyways, let me summarize this briefly here (but we should file a
> dedicated tracker here perhaps?); there are basically at least 4 major
> approaches to /etc I know of:
>
>    - What is promoted here, /etc starts out empty (let's call this the
>    "uapi ideal", though I'm not entirely sure it's truly my ideal, but that's
>    an aside)
>    - What flatcar is doing (overlayfs for /etc with the lower being the
>    defaults as installed by upstream, and /etc is a mutable persistent
>    overlayfs upper)
>    - What ostree is doing; a userspace 3 way merge; I *think* this is
>    equivalent or almost equivalent to the flatcar approach (gotta remember,
>    ostree long predates overlayfs, the ubiquitous Swiss Army knife for
>    filesystem tricks we do today)
>    - What OpenSUSE is doing (I don't quite know exactly, but it seems to
>    rely on having upstreams install stuff in /usr/etc)
>
>
We follow
https://uapi-group.org/specifications/specs/configuration_files_specification/
if the format of the configuration file allows it. If not, we only provide
a fallback config if there is none in /etc. In which case admins have to
manually merge changes.
/usr/etc is only used for configuration files where no upstream really
exists, like "services" or" protocols" or so.
I personally don't like /usr/etc, too, and I had it never on the list of
options, but this is what everybody did propose to accept this change.
Everything like /usr/share/... or similar got vetoed.

> Message ID: ***@***.***>
>


  Thorsten

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect, Future
Technologies
SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nuernberg,
Germany
Managing Director: Ivo Totev, Andrew McDonald, Werner Knoblich (HRB 36809,
AG Nürnberg)

**Comment by pemensik** [comment]
- [ ] ``/etc/resolv.conf``
- [ ] dnsmasq
- [ ] unbound
- [ ] bind9
- [ ] knot-resolver
- [ ] pdns-recursor
- [ ] dnsconfd

Any DNS caching service except systemd-resolved expects configuration in /etc/ only. With more often configured fixed DNS over TLS (or similar) service, they may have mostly static configuration, at least in some situation. But I think DNS service configuration should deserve separate issue. Especially when podman and libvirt might want to register local machine instance names to running service and not to support just single specific implementation.

But I expect they are not considered as an good alternative by systemd people, who favour their own systemd-resolved.

**Comment by septatrix** [comment]
Here are some more where I currently need tmpfile definitions to establish symlinks from `/etc` to `/usr/share/factory` for them to work properly:

- [ ] `/etc/crypto-policies` - Fedora crypto-policies)
- [ ] Lots of PAM stuff
  - [ ] `/etc/environment.conf` and `/etc/security/pam_env.conf` (`pam_env`)
  - [ ] `/etc/security/limits.conf` (`pam_limits`)
  - [ ] `/etc/security/namespace` (`pam_namespace`)
  - [ ] `/etc/security/limits.conf` (`pam_limits`)
  - [ ] `/etc/security/sepermit.conf` (`pam_sepermit`)
  - and probably many more PAM modules which are not used by default on Fedora
- [ ] `/etc/pki` - used by, well, a lot of stuff
- [ ] `/etc/ssh/sshd_config` - used by ssh server

**Comment by ReillyBrogan** [comment]
>  Lots of PAM stuff 

linux-pam supports libeconf, so `pam_env`j, `pam_limits`, and `pam_namespace` should work if you have the `--enable-vendordir` flag with the configure script. We do that on Solus and it works fine. Not sure about `pam_sepermit`, but if it doesn't work I imagine some of the econf code can be reused with it as well.

**Comment by septatrix** [comment]
> > Lots of PAM stuff
> 
> linux-pam supports libeconf, so `pam_env`j, `pam_limits`, and `pam_namespace` should work if you have the `--enable-vendordir` flag with the configure script

It seems like Fedora had it enabled at some point but [removed it again later](https://src.fedoraproject.org/rpms/pam/c/767d329677341b305c0aa3927d302ade1073cce2?branch=rawhide)

**Comment by septatrix** [comment]
Fontconfig is another contender

**Comment by ReillyBrogan** [comment]
> Fontconfig is another contender

Fontconfig is particularly problematic as it's often built and then statically linked into various applications (Chromium/Electron does this commonly) and will have sandboxes mount the `/etc/fonts` directory to be read by yet another build of fontconfig outside of the distributions control. 

Just making fontconfig hermetic-usr compatible will lead to fairly broken experiences for end-users (we tried it on Solus). I was able to make it work but it took creating a "stub" fontconfig config file in `/usr` which tmpfiles then creates a symlink at `/etc/fonts/fonts.conf` to. 

References:
- https://github.com/getsolus/packages/blob/main/packages/f/fontconfig/files/fonts.conf
- https://github.com/getsolus/packages/blob/main/packages/f/fontconfig/files/fontconfig.tmpfiles
- https://github.com/getsolus/packages/blob/main/packages/f/fontconfig/files/0003-Support-local-configs-too-for-stateless-implementati.patch

**Comment by septatrix** [comment]
> Fontconfig is particularly problematic as it's often built and then statically linked into various applications (Chromium/Electron does this commonly) and will have sandboxes mount the `/etc/fonts` directory to be read by yet another build of fontconfig outside of the distributions control.

Yes updates changes to fontconfig might take a while to trickle into projects which vendor their own copy. I do not think the sandbox is too large of a problem in itself as `/usr` is generally also included in the sandbox (or at least `/usr/share/fontconfig`) as most files from `/etc/fonts/conf.d/` are symlinks to it.

**Comment by septatrix** [comment]
Maybe not that vital but WSL: https://github.com/microsoft/WSL/issues/12299

**Comment by gioele** [comment]
> Apparmor is another one that doesn't support any kind of vendordir at the moment.

From https://gitlab.com/apparmor/apparmor/-/issues/262:

> The policy overlay is a wip and we hope to land it for the next major release this fall

**Comment by thkukuk** [comment]
> Here are a few more from my Arch machine:
> 
> *[ ]  udisks2

We tried to "fix" udisks2 with libeconf, but the upstream maintainers don't like that:
https://github.com/storaged-project/udisks/pull/1343

I don't like their idea of a "light" variant without snippets, as this does not solve the problems.
Any ideas how to convince them?

**Comment by bluca** [comment]
Getting glib to support the spec is not a bad idea, coverage would increase a lot

**Comment by karelzak** [comment]
Note that util-linux (agetty, login, chsh, chfn and su) uses /etc/login.defs if compiled without libeconf

**Comment by AdrianVovk** [comment]
Another onto the pile: XML / SGML catalogs.

For now, libraries like libxml2 are hard-coded to look for the "root" catalog in /etc/xml/catalog. Similarly, SGML catalogs are located in /etc/sgml/catalog.

So, even if you have packages install their catalogs into `/usr/share/xml/<package>/catalog.xml`, you still need to modify /etc/xml/catalog to point there. See, for instance [update-xmlcatalog(8)](https://manpages.ubuntu.com/manpages/xenial/man8/update-xmlcatalog.8.html)

**Comment by schubi2** [comment]
I have fixed krb5 (/etc/krb5.conf) https://github.com/krb5/krb5/pull/1437/files

**Comment by schubi2** [comment]
glib:
I have submitted a PR with a general function which parses configuration files in the right order and merges the parsed
values:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4671
Due this new API I hope that some projects can switch to the new configuration file order easier.

**Comment by schubi2** [comment]
> I sent a PR for bash-completion, unfortunately they were very, very hostile and unfriendly, and rejected it because "init scripts go in /etc/" and other such arguments, that are really not worth engaging with. If someone wants to pull in the patch locally, it's fairly simple: [bluca/bash-completion@9624bcb](https://github.com/bluca/bash-completion/commit/9624bcb8ad8a388366351852b37fce25ef7954ea)

Do not be frustrated. I have had similar experiences in some single projects. So what. The most of the community have been very cooperative because they have seen that these changes are really needed and useful.

**Comment by septatrix** [comment]
> I sent a PR for bash-completion, unfortunately they were very, very hostile and unfriendly, and rejected it because "init scripts go in /etc/" and other such arguments, that are really not worth engaging with. If someone wants to pull in the patch locally, it's fairly simple: [bluca/bash-completion@9624bcb](https://github.com/bluca/bash-completion/commit/9624bcb8ad8a388366351852b37fce25ef7954ea)

Please don't misrepresent the facts, you just have been talking around each other leading to no good discussion culture on both sides. One maintainer claiming that you rage-quit might have been unjust but apart from that I do not see any purposeful hostility. They are evaluating it critically and have not made a final call on whether to accept or reject the PR.
It's you who abstained from further discussions there but that is your good right if you think the discussion is leading nowhere and would rather spend your time on other things.
Instead I have tried to clear up some of the open points/confusion and might try to move it forward (though I too have limited time to spend on that). For everyone who wants to follow along, please keep the discussion civil: https://github.com/scop/bash-completion/pull/1399

**Comment by bluca** [comment]
> I do not see any purposeful hostility

If getting called a liar over some very obvious misunderstandings that would take literally 5 seconds of actually reading what was written with a bare minimum of attention is not hostility, then we may have very different concepts of what that means. It's important to be able to discern between genuine and good faith questions and discussions, and when someone is just sealioning, to avoid wasting time and effort when there's no point in doing so. As someone said earlier, there will always be a tiny minority of projects that will be hostile no matter what. Best to leave them alone and know how to work around them and eventually drop them and replace them.

**Comment by JustSoup312** [comment]
Added a pseudo-related PR to the [meson project](https://github.com/mesonbuild/meson/pull/14919). From a disto packager perspective, getting stuff like this into build-systems seems like a good push.

**Comment by behrmann** [comment]
> Logrotate is another one

There's an issue for that https://github.com/logrotate/logrotate/issues/436 by @thkukuk and I think they consider it mostly solved via https://github.com/logrotate/logrotate/pull/473. So this might be solved via distro-packaging by shipping distro logrotate config in `/usr` and including config in search path order with distro config shipped last.

**Comment by AdrianVovk** [comment]
No unfortunately that isn't quite the same. Because not only the contents of files can change, but also the actual existence/folder structure of the files.

Then you're either missing a config file, or have a config file pointing at a location that doesn't exist anymore, etc

The nail in the coffin for this approach is that you can't tell the difference between a file the admin deleted and a file that's simply missing due to an old version of the OS being installed previously. So you can't even have a separate fix-up step without un-deleting config files an admin had deleted

**Comment by zyga** [comment]
I'd like to make progress on apparmor upstream
